#+TITLE: Software
#+HTML_LINK_HOME: ./index.html
#+HTML_LINK_UP: ./index.html

** Software Selection

The software used will also be driven primarily by what can be
discovered through navigation, with a useful initial directory being
provided by the [[file:sources.org::#gnumanuals][GNU Manuals]] (and a more comprehensive selection in the
linked Free Software Directory which will be explored to fill possible
gaps).

This will follow a general pattern of slow expansion based on
acquiring deep knowledge of the adopted software through both
bottom-up parsing of the systems and back-filling of such information.

** [[file:coding_style.org][My Coding Style]]
** Toolbox

Here I'll catalog some of the software that I've currently adopted for
personal use. Many of these I'll also use where appropriate
professionally but there I'm more likely to drift to anything more
widely palatable or organizationally prudent.

[[file:my_software_configuration.org][My Software Configuration]]

*** Bash

There are newer cleaner shells around now, but bash still seems to be
the most widely available alternative to the Bourne shell. I tend to
think bash is often derided due to lack of understanding of some of
the choices that lurk within it. I've personally used it for some
cases that may have warranted an alternative, but I've also seen
people apply other languages inappropriately (in my opinion) where
bash could be used (most clearly in cases where additional hurdles or
limitations are introduced such as by needing to communicate
information back to the shell or when an inconsistent or restricted
interaction model is imposed. On the other hand I am keeping an eye on
the prospect of abandoning bash in one of two fairly opposite
directions.

Bash contains a bit more implementation noise than I'd like - the code
could be significantly streamlined if it made heavier use of reused
code and concepts and dropped some redundant functionality. Perhaps
more significantly it also has some quirks that it has acquired over
the years that could be simplified and made more consistent (such as
its initialization process). These factors leave me interested in a
leaner implementation of a subset of the existing implementation.

On the other hand I'm interested in a more ambitious shift in how to
interact with a machine. Bash and POSIX shells generally reflect a
very elegant model of uniform pipes and filters atop supporting ideas
such as software tools and treating everything as a file. Such
concepts tend to seemingly be not particularly well understood and
correspondingly underutilized by most developers in the industry.
I don't have a particularly clear picture of how to realize an
improvement (so this is a nebulous interest), but it seems as though
there may be some avenues to explore. Managing of multiple streams in
a shell can be awkward, though the prospect of providing more
sophisticated behavior seems dangerous in that it could complicate the
more standard and simple use cases. Another possible wrinkle is the
division between orchestrating commands and defining logic directly.
This is likely often a source of consternation for those that may not
recognize that serving both roles is a source for many of bash's
quirks, but generally it would be ideal if the provided REPL was able
to satisfy both needs with a more uniform interface. More
significantly the split also potentially ties in with grander
perspectives around boundaries imposed around which logic will be
executed where. This overall concern ties in with thoughts
expressed [[file:programming_languages_are_harmful.org][elsewhere]] which may be explored over as long period.

*** Emacs

[[file:sources.org::#emacs][Emacs]] is a piece of software that I periodically swear off and then
return to with my tail between my legs. I've adopted it for several
reasons over the years but also moved away from it pursuit of
something smaller and more in-line with the ideology of software
tools. Currently it appeals to me as starting position for some larger
ideas around how I may want my use of computers to evolve which will
be elaborated upon as they are explored, this somewhat ties in with
tongue-in-cheek perspective of Emacs being more of an operating system
than an editor.

[[./emacs_init.org][My Emacs Configuration]]

** TODO Test Pyramid
